name: kubernetes
description: A feature-rich and fully-fledged Kubernetes client for Dart/Flutter.
version: 1.26.0+5
homepage: https://pwa.ir
repository: https://github.com/xclud/dart_kubernetes

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  http: ">=0.13.1 <2.0.0"

dev_dependencies:
  test: ^1.22.0
  lints: ^2.0.0
